### ISSUE TITLE
Error in F8

### ISSUE THREAD

**Issue by esFer102** [VORPCORE/vorp_fishing#3]
Why this happens?
![image](https://user-images.githubusercontent.com/58149189/176286639-da37b1ec-ceff-4997-91cc-98f98390193f.png)

**Comment by esFer102** [comment]
The error doesn't stop spamming, I've only changed locale file.
![image](https://user-images.githubusercontent.com/58149189/176287943-29783d76-ebc7-4bfb-8238-9f617f87e4a2.png)

**Comment by DerHobbs** [comment]
ah wait, that's fishing C#

**Comment by DerHobbs** [comment]
It's best to download it and try again without changes

**Comment by esFer102** [comment]
OK, i'll try it. But the thing is that i've tried on lua too but it doesn't work for me. I try to catch a fish but it doesn't works propperly.

**Comment by esFer102** [comment]
Doesn't work. I've reinstalled it but it gives me the same error.

**Comment by DerHobbs** [comment]
Ok, have you tried vorp_fishing lua? I use this myself and it works fine.

**Comment by esFer102** [comment]
Yes, but i can't fish properly. Look I'll send you now a video.

**Comment by DerHobbs** [comment]
https://streamable.com/st568z

But that is the LUA version

**Comment by esFer102** [comment]
Okey sorry, it was my fault. It works properly, I thank you very much for your time.
