### ISSUE TITLE
Bait doesn't work 

### ISSUE THREAD

**Issue by cha-afk** [VORPCORE/vorp_fishing#4]
When i double click on an item it won't be used 

exemple of my db : 
![image](https://github.com/VORPCORE/vorp_fishing/assets/61283384/6f471e2e-c6fd-4c37-a89a-c4912fcbe9e1)

i didn't mess with the config , even in the previous versions it won't work for me

**Comment by cha-afk** [comment]
fixed. double click to use in the inventory config file doesn't get it to work for some reasons , so i'm using , right click then use .

**Comment by outsider31000** [comment]
maybe try to update inventory. cause its an item it should work for all items, they work for me
